from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField, StringField, DecimalField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User

class LoginForm(FlaskForm):
    username = StringField('Логин', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired(), Length(min=4, max=80)])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')


class FormDataForm(FlaskForm):
    labour_population = DecimalField('Labour Population', validators=[DataRequired()])
    labour_constant_population = DecimalField('Labour Constant Population', validators=[DataRequired()])
    labour_labour = DecimalField('Labour Labour', validators=[DataRequired()])
    labour_goverment_workers = DecimalField('Labour Goverment Workers', validators=[DataRequired()])
    labour_private_labour = DecimalField('Labour Private Labour', validators=[DataRequired()])
    labour_private_ogorod = DecimalField('Labour Private Ogorod', validators=[DataRequired()])
    labour_total_econ_inactive_population = DecimalField('Labour Total Econ Inactive Population', validators=[DataRequired()])
    labour_unemployed = DecimalField('Labour Unemployed', validators=[DataRequired()])
    labour_household_size = DecimalField('Labour Household Size', validators=[DataRequired()])
    labour_average_income_family = DecimalField('Labour Average Income Family', validators=[DataRequired()])
    house_total_dvor = DecimalField('House Total Dvor', validators=[DataRequired()])
    house_zaselen_dvor = DecimalField('House Zaselen Dvor', validators=[DataRequired()])
    dh_count = DecimalField('DH Count', validators=[DataRequired()])
    dx_number_ogorodov = DecimalField('DX Number Ogorodov', validators=[DataRequired()])
    dx_cx_land = DecimalField('DX CX Land', validators=[DataRequired()])
    dx_pashnya = DecimalField('DX Pashnya', validators=[DataRequired()])
    dx_mnogoletnie = DecimalField('DX Mnogoletnie', validators=[DataRequired()])
    dx_zelej = DecimalField('DX Zelej', validators=[DataRequired()])
    dx_pastbishe = DecimalField('DX Pastbishe', validators=[DataRequired()])
    dx_senokosy = DecimalField('DX Senokosy', validators=[DataRequired()])
    dx_ogorody = DecimalField('DX Ogorody', validators=[DataRequired()])
    dx_sad = DecimalField('DX Sad', validators=[DataRequired()])
    dx_urojai = DecimalField('DX Urojai', validators=[DataRequired()])
    dx_cucumber = DecimalField('DX Cucumber', validators=[DataRequired()])
    dx_tomato = DecimalField('DX Tomato', validators=[DataRequired()])
    dx_potato = DecimalField('DX Potato', validators=[DataRequired()])
    dx_kapusta = DecimalField('DX Kapusta', validators=[DataRequired()])
    dx_carrot = DecimalField('DX Carrot', validators=[DataRequired()])
    dx_svekla = DecimalField('DX Svekla', validators=[DataRequired()])
    dx_sweet_peper = DecimalField('DX Sweet Peper', validators=[DataRequired()])
    dx_baklajan = DecimalField('DX Baklajan', validators=[DataRequired()])
    dx_kabachek = DecimalField('DX Kabachek', validators=[DataRequired()])
    dx_onion = DecimalField('DX Onion', validators=[DataRequired()])
    dx_chesnok = DecimalField('DX Chesnok', validators=[DataRequired()])
    dx_redis = DecimalField('DX Redis', validators=[DataRequired()])
    dx_korm = DecimalField('DX Korm', validators=[DataRequired()])
    dx_fruits = DecimalField('DX Fruits', validators=[DataRequired()])
    kx_amount = DecimalField('KX Amount', validators=[DataRequired()])
    kz_cx_land = DecimalField('KZ CX Land', validators=[DataRequired()])
    kx_pansya = DecimalField('KX Pansya', validators=[DataRequired()])
    kx_mnogoletnie = DecimalField('KX Mnogoletnie', validators=[DataRequired()])
    kx_zelej = DecimalField('KX Zelej', validators=[DataRequired()])
    kx_pastbishe = DecimalField('KX Pastbishe', validators=[DataRequired()])
    kx_senokosy = DecimalField('KX Senokosy', validators=[DataRequired()])
    kx_urojai = DecimalField('KX Urojai', validators=[DataRequired()])
    kx_zerno = DecimalField('KX Zerno', validators=[DataRequired()])
    kx_rice = DecimalField('KX Rice', validators=[DataRequired()])
    kx_maslichnye = DecimalField('KX Maslichnye', validators=[DataRequired()])
    kx_korm = DecimalField('KX Korm', validators=[DataRequired()])
    kx_mnogoletnie_derevo = DecimalField('KX Mnogoletnie Derevo', validators=[DataRequired()])
    kz_cx_land_reserve = DecimalField('KZ CX Land Reserve', validators=[DataRequired()])
    kx_pansya_reserve = DecimalField('KX Pansya Reserve', validators=[DataRequired()])
    kx_mnogoletnie_reserve = DecimalField('KX Mnogoletnie Reserve', validators=[DataRequired()])
    kx_zelej_reserve = DecimalField('KX Zelej Reserve', validators=[DataRequired()])
    kx_pastbishe_reserve = DecimalField('KX Pastbishe Reserve', validators=[DataRequired()])
    kx_senokosy_reserve = DecimalField('KX Senokosy Reserve', validators=[DataRequired()])
    infrastructure_polivochnaya_sistema_ = DecimalField('Infrastructure Polivochnaya Sistema', validators=[DataRequired()])
    infrastructure_polivochnaya_sistema_isused = DecimalField('Infrastructure Polivochnaya Sistema Isused', validators=[DataRequired()])
    infrastructure_polivy = DecimalField('Infrastructure Polivy', validators=[DataRequired()])
    infrastructure_mtm = DecimalField('Infrastructure Mtm', validators=[DataRequired()])
    infrastructure_mtm_isused = DecimalField('Infrastructure Mtm Isused', validators=[DataRequired()])
    infrastructure_slad = DecimalField('Infrastructure Slad', validators=[DataRequired()])
    infrastructure_slad_isused = DecimalField('Infrastructure Slad Isused', validators=[DataRequired()])
    infrastructure_garage = DecimalField('Infrastructure Garage', validators=[DataRequired()])
    infrastructure_garage_isused = DecimalField('Infrastructure Garage Isused', validators=[DataRequired()])
    infrastructure_cycsterny = DecimalField('Infrastructure Cycsterny', validators=[DataRequired()])
    infrastructure_cycsterny_isused = DecimalField('Infrastructure Cycsterny Isused', validators=[DataRequired()])
    infrastructure_transformator = DecimalField('Infrastructure Transformator', validators=[DataRequired()])
    infrastructure_transformator_isused = DecimalField('Infrastructure Transformator Isused', validators=[DataRequired()])
    specialization_rastenivodstvo = DecimalField('Specialization Rastenivodstvo', validators=[DataRequired()])
    animal_dvor = DecimalField('Animal Dvor', validators=[DataRequired()])
    animal_skot_bird = DecimalField('Animal Skot Bird', validators=[DataRequired()])
    animal_cx_land = DecimalField('Animal CX Land', validators=[DataRequired()])
    animal_pashnya = DecimalField('Animal Pashnya', validators=[DataRequired()])
    animal_mnogolet = DecimalField('Animal Mnogolet', validators=[DataRequired()])
    animal_zalej = DecimalField('Animal Zalej', validators=[DataRequired()])
    animal_pastbisha = DecimalField('Animal Pastbisha', validators=[DataRequired()])
    animal_senokos = DecimalField('Animal Senokos', validators=[DataRequired()])
    animal_ogorod = DecimalField('Animal Ogorod', validators=[DataRequired()])
    animal_sad = DecimalField('Animal Sad', validators=[DataRequired()])
    animal_krs_milk = DecimalField('Animal KRS Milk', validators=[DataRequired()])
    animal_krs_meat = DecimalField('Animal KRS Meat', validators=[DataRequired()])
    animal_sheep = DecimalField('Animal Sheep', validators=[DataRequired()])
    animal_kozel = DecimalField('Animal Kozel', validators=[DataRequired()])
    animal_horse = DecimalField('Animal Horse', validators=[DataRequired()])
    animal_camel = DecimalField('Animal Camel', validators=[DataRequired()])
    animal_pig = DecimalField('Animal Pig', validators=[DataRequired()])
    animal_chicken = DecimalField('Animal Chicken', validators=[DataRequired()])
    animal_gusi = DecimalField('Animal Gusi', validators=[DataRequired()])
    animal_duck = DecimalField('Animal Duck', validators=[DataRequired()])
    animal_induk = DecimalField('Animal Induk', validators=[DataRequired()])
    animal_mik_total = DecimalField('Animal Mik Total', validators=[DataRequired()])
    animal_milk_cow = DecimalField('Animal Milk Cow', validators=[DataRequired()])
    animal_milkrate_cow = DecimalField('Animal Milkrate Cow', validators=[DataRequired()])
    animal_mil_kozel = DecimalField('Animal Mil Kozel', validators=[DataRequired()])
    animal_milrate_kozel = DecimalField('Animal Milrate Kozel', validators=[DataRequired()])
    animal_milk_horse = DecimalField('Animal Milk Horse', validators=[DataRequired()])
    animal_milkrate_horse = DecimalField('Animal Milkrate Horse', validators=[DataRequired()])
    animal_milk_camel = DecimalField('Animal Milk Camel', validators=[DataRequired()])
    animal_milkrate_camel = DecimalField('Animal Milkrate Camel', validators=[DataRequired()])
    animal_meat_total = DecimalField('Animal Meat Total', validators=[DataRequired()])
    animal_meat_cow = DecimalField('Animal Meat Cow', validators=[DataRequired()])
    animal_meat_sheep = DecimalField('Animal Meat Sheep', validators=[DataRequired()])
    animal_meat_horse = DecimalField('Animal Meat Horse', validators=[DataRequired()])
    animal_meat_pig = DecimalField('Animal Meat Pig', validators=[DataRequired()])
    animal_meat_camel = DecimalField('Animal Meat Camel', validators=[DataRequired()])
    animal_meat_chicken = DecimalField('Animal Meat Chicken', validators=[DataRequired()])
    animal_meat_duck = DecimalField('Animal Meat Duck', validators=[DataRequired()])
    animal_meat_gusi = DecimalField('Animal Meat Gusi', validators=[DataRequired()])
    animal_egg_total = DecimalField('Animal Egg Total', validators=[DataRequired()])
    animal_egg_chicken = DecimalField('Animal Egg Chicken', validators=[DataRequired()])
    animal_egg_gusi = DecimalField('Animal Egg Gusi', validators=[DataRequired()])
    animal_egg_perepel = DecimalField('Animal Egg Perepel', validators=[DataRequired()])
    animal_transformator = DecimalField('Animal Transformator', validators=[DataRequired()])
    animal_transformator_isused = DecimalField('Animal Transformator Isused', validators=[DataRequired()])
    specialization_animal = DecimalField('Specialization Animal', validators=[DataRequired()])
    noncx_sto = DecimalField('Noncx Sto', validators=[DataRequired()])
    noncx_sto_needs = DecimalField('Noncx Sto Needs', validators=[DataRequired()])
    noncx_kindergarden = DecimalField('Noncx Kindergarden', validators=[DataRequired()])
    noncx_kindergarden_needs = DecimalField('Noncx Kindergarden Needs', validators=[DataRequired()])
    noncx_souvenier = DecimalField('Noncx Souvenier', validators=[DataRequired()])
    noncx_souvenier_needs = DecimalField('Noncx Souvenier Needs', validators=[DataRequired()])
    noncx_pc_service = DecimalField('Noncx PC Service', validators=[DataRequired()])
    noncx_pc_service_needs = DecimalField('Noncx PC Service Needs', validators=[DataRequired()])
    noncx_store = DecimalField('Noncx Store', validators=[DataRequired()])
    noncx_store_needs = DecimalField('Noncx Store Needs', validators=[DataRequired()])
    noncx_remont_bytovoi_tech = DecimalField('Noncx Remont Bytovoi Tech', validators=[DataRequired()])
    noncx_remont_bytovoi_tech_needs = DecimalField('Noncx Remont Bytovoi Tech Needs', validators=[DataRequired()])
    noncx_metal = DecimalField('Noncx Metal', validators=[DataRequired()])
    noncx_metal_needs = DecimalField('Noncx Metal Needs', validators=[DataRequired()])
    noncx_accounting = DecimalField('Noncx Accounting', validators=[DataRequired()])
    noncx_accounting_needs = DecimalField('Noncx Accounting Needs', validators=[DataRequired()])
    noncx_photo = DecimalField('Noncx Photo', validators=[DataRequired()])
    noncx_photo_needs = DecimalField('Noncx Photo Needs', validators=[DataRequired()])
    noncx_turism = DecimalField('Noncx Turism', validators=[DataRequired()])
    noncx_turism_needs = DecimalField('Noncx Turism Needs', validators=[DataRequired()])
    noncx_rent = DecimalField('Noncx Rent', validators=[DataRequired()])
    noncx_rent_needs = DecimalField('Noncx Rent Needs', validators=[DataRequired()])
    noncx_cargo = DecimalField('Noncx Cargo', validators=[DataRequired()])
    noncx_cargo_needs = DecimalField('Noncx Cargo Needs', validators=[DataRequired()])
    noncx_massage = DecimalField('Noncx Massage', validators=[DataRequired()])
    noncx_massage_needs = DecimalField('Noncx Massage Needs', validators=[DataRequired()])
    noncx_foodcourt = DecimalField('Noncx Foodcourt', validators=[DataRequired()])
    noncx_foodcourt_needs = DecimalField('Noncx Foodcourt Needs', validators=[DataRequired()])
    noncx_cleaning = DecimalField('Noncx Cleaning', validators=[DataRequired()])
    noncx_cleaning_needs = DecimalField('Noncx Cleaning Needs', validators=[DataRequired()])
    noncx_beuty = DecimalField('Noncx Beuty', validators=[DataRequired()])
    noncx_beuty_needs = DecimalField('Noncx Beuty Needs', validators=[DataRequired()])
    noncx_carwash = DecimalField('Noncx Carwash', validators=[DataRequired()])
    noncx_carwash_needs = DecimalField('Noncx Carwash Needs', validators=[DataRequired()])
    noncx_atelie = DecimalField('Noncx Atelie', validators=[DataRequired()])
    noncx_atelie_needs = DecimalField('Noncx Atelie Needs', validators=[DataRequired()])
    noncx_others = DecimalField('Noncx Others', validators=[DataRequired()])
    noncx_others_needs = DecimalField('Noncx Others Needs', validators=[DataRequired()])
    noncx_stroika = DecimalField('Noncx Stroika', validators=[DataRequired()])
    noncx_stroika_needs = DecimalField('Noncx Stroika Needs', validators=[DataRequired()])
    noncx_mebel = DecimalField('Noncx Mebel', validators=[DataRequired()])
    noncx_mebel_needs = DecimalField('Noncx Mebel Needs', validators=[DataRequired()])
    noncx_stroi_material = DecimalField('Noncx Stroi Material', validators=[DataRequired()])
    noncx_stroi_material_needs = DecimalField('Noncx Stroi Material Needs', validators=[DataRequired()])
    noncx_svarka = DecimalField('Noncx Svarka', validators=[DataRequired()])
    noncx_svarka_needs = DecimalField('Noncx Svarka Needs', validators=[DataRequired()])
    noncx_woodworking = DecimalField('Noncx Woodworking', validators=[DataRequired()])
    noncx_woodworking_needs = DecimalField('Noncx Woodworking Needs', validators=[DataRequired()])
    noncx_others_uslugi = DecimalField('Noncx Others Uslugi', validators=[DataRequired()])
    noncx_others_needs_uslugi = DecimalField('Noncx Others Needs Uslugi', validators=[DataRequired()])
    manufacture_milk = DecimalField('Manufacture Milk', validators=[DataRequired()])
    manufacture_milk_needs = DecimalField('Manufacture Milk Needs', validators=[DataRequired()])
    manufacture_meat = DecimalField('Manufacture Meat', validators=[DataRequired()])
    manufacture_meat_needs = DecimalField('Manufacture Meat Needs', validators=[DataRequired()])
    manufacture_vegetables = DecimalField('Manufacture Vegetables', validators=[DataRequired()])
    manufacture_vegetables_needs = DecimalField('Manufacture Vegetables Needs', validators=[DataRequired()])
    manufacture_mayo = DecimalField('Manufacture Mayo', validators=[DataRequired()])
    manufacture_mayo_needs = DecimalField('Manufacture Mayo Needs', validators=[DataRequired()])
    manufacture_fish = DecimalField('Manufacture Fish', validators=[DataRequired()])
    manufacture_fish_needs = DecimalField('Manufacture Fish Needs', validators=[DataRequired()])
    manufacture_choco = DecimalField('Manufacture Choco', validators=[DataRequired()])
    manufacture_choco_needs = DecimalField('Manufacture Choco Needs', validators=[DataRequired()])
    manufacture_beer = DecimalField('Manufacture Beer', validators=[DataRequired()])
    manufacture_beer_needs = DecimalField('Manufacture Beer Needs', validators=[DataRequired()])
    manufacture_vodka = DecimalField('Manufacture Vodka', validators=[DataRequired()])
    manufacture_vodka_needs = DecimalField('Manufacture Vodka Needs', validators=[DataRequired()])
    manufacture_honey = DecimalField('Manufacture Honey', validators=[DataRequired()])
    manufacture_honey_needs = DecimalField('Manufacture Honey Needs', validators=[DataRequired()])
    manufacture_polufabricat = DecimalField('Manufacture Polufabricat', validators=[DataRequired()])
    manufacture_polufabricat_needs = DecimalField('Manufacture Polufabricat Needs', validators=[DataRequired()])
    manufacture_bread = DecimalField('Manufacture Bread', validators=[DataRequired()])
    manufacture_bread_needs = DecimalField('Manufacture Bread Needs', validators=[DataRequired()])
    manufacture_others = DecimalField('Manufacture Others', validators=[DataRequired()])
    manufacture_others_needs = DecimalField('Manufacture Others Needs', validators=[DataRequired()])
    credit_amount = DecimalField('Credit Amount', validators=[DataRequired()])
    credit_total = DecimalField('Credit Total', validators=[DataRequired()])
    credit_average_total = DecimalField('Credit Average Total', validators=[DataRequired()])
    credit_zalog = DecimalField('Credit Zalog', validators=[DataRequired()])

    submit = SubmitField('Submit')
