from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField, StringField, DecimalField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User

class LoginForm(FlaskForm):
    username = StringField('Логин', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired(), Length(min=4, max=80)])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')


class FormDataForm(FlaskForm):
    labour_population = DecimalField('Численность Населения', validators=[DataRequired()])
    labour_constant_population = DecimalField('из них постоянно проживающих', validators=[DataRequired()])
    labour_labour = DecimalField('Рабочая сила', validators=[DataRequired()])
    labour_government_workers = DecimalField('Занятое население в бюджетной сфере', validators=[DataRequired()])
    labour_private_labour = DecimalField('Занятое население в частном секторе', validators=[DataRequired()])
    labour_private_ogorod = DecimalField('из них занятое население в личном подсобном хозяйстве', validators=[DataRequired()])
    labour_total_econ_inactive_population = DecimalField('Лица, не входящие в состав рабочей силы', validators=[DataRequired()])
    labour_unemployed = DecimalField('Безработные', validators=[DataRequired()])
    labour_household_size = DecimalField('Средний размер домашних хозяйств', validators=[DataRequired()])
    labour_average_income_family = DecimalField('Средний доход на одну семью, в месяц', validators=[DataRequired()])
    house_total_dvor = DecimalField('Общее количество дворов (частные дома, квартиры в многоквартирном доме, точки чабана, иное)', validators=[DataRequired()])
    house_zaselen_dvor = DecimalField('из них количество заселенных дворов', validators=[DataRequired()])
    dh_count = DecimalField('Количество домашних хозяйств', validators=[DataRequired()])
    dx_number_ogorodov = DecimalField('Количество домашних хозяйств имеющих участки (огороды, сады, приусадебные участки)', validators=[DataRequired()])
    dx_cx_land = DecimalField('Сельскохозяйственные угодья домашних хозяйств', validators=[DataRequired()])
    dx_pashnya = DecimalField('Пашня', validators=[DataRequired()])
    dx_mnogoletnie = DecimalField('Многолетние насаждения', validators=[DataRequired()])
    dx_zelej = DecimalField('Залежь', validators=[DataRequired()])
    dx_pastbishe = DecimalField('Пастбища', validators=[DataRequired()])
    dx_senokosy = DecimalField('Сенокосы', validators=[DataRequired()])
    dx_ogorody = DecimalField('Огороды', validators=[DataRequired()])
    dx_sad = DecimalField('Сады', validators=[DataRequired()])
    dx_urojai = DecimalField('Объем урожая сельскохозяйственных культур в домашних хозяйствах, всего', validators=[DataRequired()])
    dx_cucumber = DecimalField('Огурцы', validators=[DataRequired()])
    dx_tomato = DecimalField('Помидоры', validators=[DataRequired()])
    dx_potato = DecimalField('Картофель', validators=[DataRequired()])
    dx_kapusta = DecimalField('Капуста', validators=[DataRequired()])
    dx_carrot = DecimalField('Морковь', validators=[DataRequired()])
    dx_svekla = DecimalField('Свекла', validators=[DataRequired()])
    dx_sweet_peper = DecimalField('Сладкий перец', validators=[DataRequired()])
    dx_baklajan = DecimalField('Баклажаны', validators=[DataRequired()])
    dx_kabachek = DecimalField('Кабачки', validators=[DataRequired()])
    dx_onion = DecimalField('Лук', validators=[DataRequired()])
    dx_chesnok = DecimalField('Чеснок', validators=[DataRequired()])
    dx_redis = DecimalField('Редис', validators=[DataRequired()])
    dx_korm = DecimalField('Кормовые культуры', validators=[DataRequired()])
    dx_fruits = DecimalField('Культуры многолетние (плодовые, ягодные насаждения)', validators=[DataRequired()])
    kx_amount = DecimalField('Количество крестьянских хозяйств', validators=[DataRequired()])
    kz_cx_land = DecimalField('Сельскохозяйственные угодья крестьянских хозяйств', validators=[DataRequired()])
    kx_pansya = DecimalField('Пашня', validators=[DataRequired()])
    kx_mnogoletnie = DecimalField('Многолетние насаждения', validators=[DataRequired()])
    kx_zelej = DecimalField('Залежь', validators=[DataRequired()])
    kx_pastbishe = DecimalField('Пастбища', validators=[DataRequired()])
    kx_senokosy = DecimalField('Сенокосы', validators=[DataRequired()])
    kx_urojai = DecimalField('Объем урожая сельскохозяйственных культур в крестьянских хозяйствах, всего', validators=[DataRequired()])
    kx_zerno = DecimalField('Зерновые и бобовые всех видов', validators=[DataRequired()])
    kx_rice = DecimalField('Рис', validators=[DataRequired()])
    kx_maslichnye = DecimalField('Масличные всех видов', validators=[DataRequired()])
    kx_korm = DecimalField('Кормовые культуры', validators=[DataRequired()])
    kx_mnogoletnie_derevo = DecimalField('Культуры многолетние (плодовые деревья, кустарники)', validators=[DataRequired()])
    kz_cx_land_reserve = DecimalField('Резерв увеличения земельных угодий за счет фонда неиспользуемых и/или изъятых земель', validators=[DataRequired()])
    kx_pansya_reserve = DecimalField('Пашня', validators=[DataRequired()])
    kx_mnogoletnie_reserve = DecimalField('Многолетние насаждения', validators=[DataRequired()])
    kx_zelej_reserve = DecimalField('Залежь', validators=[DataRequired()])
    kx_pastbishe_reserve = DecimalField('Пастбища', validators=[DataRequired()])
    kx_senokosy_reserve = DecimalField('Сенокосы', validators=[DataRequired()])
    infrastructure_polivochnaya_sistema_ = DecimalField('Обеспеченность водой для полива', validators=[DataRequired()]) # наличие
    infrastructure_polivochnaya_sistema_isused = DecimalField('Обеспеченность водой для полива', validators=[DataRequired()]) # использовуется
    infrastructure_polivy = DecimalField('Процент покрытия поливом посевных площадей', validators=[DataRequired()])
    infrastructure_mtm = DecimalField('Здание МТМ (машино-тракторная мастерская)', validators=[DataRequired()]) # наличие
    infrastructure_mtm_isused = DecimalField('Здание МТМ (машино-тракторная мастерская)', validators=[DataRequired()]) # использовуется
    infrastructure_slad = DecimalField('Склады для хранения сырья и готовой продукции', validators=[DataRequired()])
    infrastructure_slad_isused = DecimalField('Склады для хранения сырья и готовой продукции', validators=[DataRequired()])
    infrastructure_garage = DecimalField('Гаражи, ангары для хранения с/х техники и автотранспорта', validators=[DataRequired()])
    infrastructure_garage_isused = DecimalField('Гаражи, ангары для хранения с/х техники и автотранспорта', validators=[DataRequired()])
    infrastructure_cycsterny = DecimalField('Цистерны для хранения ГСМ (горюче-смазочные материалы)', validators=[DataRequired()])
    infrastructure_cycsterny_isused = DecimalField('Цистерны для хранения ГСМ (горюче-смазочные материалы)', validators=[DataRequired()])
    infrastructure_transformator = DecimalField('Трансформаторная электро-подстанция', validators=[DataRequired()])
    infrastructure_transformator_isused = DecimalField('Трансформаторная электро-подстанция', validators=[DataRequired()])
    specialization_rastenivodstvo = DecimalField('Специализация в растениеводстве', validators=[DataRequired()])
    animal_dvor = DecimalField('Общее число дворов', validators=[DataRequired()])
    animal_skot_bird = DecimalField('из них имеет скот и птицу', validators=[DataRequired()])
    animal_cx_land = DecimalField('Сельскохозяйственные угодья домашних хозяйств', validators=[DataRequired()])
    animal_pashnya = DecimalField('Пашня', validators=[DataRequired()])
    animal_mnogolet = DecimalField('Многолетние насаждения', validators=[DataRequired()])
    animal_zalej = DecimalField('Залежь', validators=[DataRequired()])
    animal_pastbisha = DecimalField('Пастбища', validators=[DataRequired()])
    animal_senokos = DecimalField('Сенокосы', validators=[DataRequired()])
    animal_ogorod = DecimalField('Огороды', validators=[DataRequired()])
    animal_sad = DecimalField('Сады', validators=[DataRequired()])
    animal_krs_milk = DecimalField('КРС молочный', validators=[DataRequired()])
    animal_krs_meat = DecimalField('КРС мясной ', validators=[DataRequired()])
    animal_sheep = DecimalField('Овцы, бараны', validators=[DataRequired()])
    animal_kozel = DecimalField('Козы, козлы', validators=[DataRequired()])
    animal_horse = DecimalField('Лошади', validators=[DataRequired()])
    animal_camel = DecimalField('Верблюды', validators=[DataRequired()])
    animal_pig = DecimalField('Свиньи', validators=[DataRequired()])
    animal_chicken = DecimalField('Куры', validators=[DataRequired()])
    animal_gusi = DecimalField('Гуси', validators=[DataRequired()])
    animal_duck = DecimalField('Утки', validators=[DataRequired()])
    animal_induk = DecimalField('Индюки', validators=[DataRequired()])
    animal_mik_total = DecimalField('Валовой надой молока, тонн в год, всего', validators=[DataRequired()])
    animal_milk_cow = DecimalField('Валовой надой коровьего молока', validators=[DataRequired()])
    animal_milkrate_cow = DecimalField('Доля коровьего молока', validators=[DataRequired()])
    animal_mil_kozel = DecimalField('Валовой надой козьего молока', validators=[DataRequired()])
    animal_milrate_kozel = DecimalField('Доля козьего молока', validators=[DataRequired()])
    animal_milk_horse = DecimalField('Валовой надой кобыльего молока', validators=[DataRequired()])
    animal_milkrate_horse = DecimalField('Доля молока кобыльего молока', validators=[DataRequired()])
    animal_milk_camel = DecimalField('Валовой надой верблюжьего молока', validators=[DataRequired()])
    animal_milkrate_camel = DecimalField('Доля верблюжьего молока', validators=[DataRequired()])
    animal_meat_total = DecimalField('Валовой сбор всего мяса', validators=[DataRequired()])
    animal_meat_cow = DecimalField('Говядина', validators=[DataRequired()])
    animal_meat_sheep = DecimalField('Баранина', validators=[DataRequired()])
    animal_meat_horse = DecimalField('Конина', validators=[DataRequired()])
    animal_meat_pig = DecimalField('Свинина', validators=[DataRequired()])
    animal_meat_camel = DecimalField('Верблюжатина', validators=[DataRequired()])
    animal_meat_chicken = DecimalField('Куриное мясо', validators=[DataRequired()])
    animal_meat_duck = DecimalField('Утиное мясо', validators=[DataRequired()])
    animal_meat_gusi = DecimalField('Гусиное мясо', validators=[DataRequired()])
    animal_egg_total = DecimalField('Валовой сбор яиц', validators=[DataRequired()])
    animal_egg_chicken = DecimalField('Яйца куриные', validators=[DataRequired()])
    animal_egg_gusi = DecimalField('Яйца гусиные', validators=[DataRequired()])
    animal_egg_perepel = DecimalField('Яйца перепелиные', validators=[DataRequired()])
    animal_transformator = DecimalField('Трансформаторная электро-подстанция', validators=[DataRequired()])
    animal_transformator_isused = DecimalField('Трансформаторная электро-подстанция', validators=[DataRequired()])
    specialization_animal = DecimalField('Специализация в животноводстве', validators=[DataRequired()])
    noncx_sto = DecimalField('Автосервис (СТО, шиномонтаж, замена автозапчастей и т.д.)', validators=[DataRequired()]) # единиц
    noncx_sto_needs = DecimalField('Автосервис (СТО, шиномонтаж, замена автозапчастей и т.д.)', validators=[DataRequired()]) # потребитель
    noncx_kindergarden = DecimalField('Детские центры развития, репетиторские услуги, языковые курсы', validators=[DataRequired()])
    noncx_kindergarden_needs = DecimalField('Детские центры развития, репетиторские услуги, языковые курсы', validators=[DataRequired()])
    noncx_souvenier = DecimalField('Изготовление сувениров, украшений из различных материалов', validators=[DataRequired()])
    noncx_souvenier_needs = DecimalField('Изготовление сувениров, украшений из различных материалов', validators=[DataRequired()])
    noncx_pc_service = DecimalField('Компьютерные услуги', validators=[DataRequired()])
    noncx_pc_service_needs = DecimalField('Компьютерные услуги', validators=[DataRequired()])
    noncx_store = DecimalField('Магазин (минимаркет, строительных материалов, автозапчастей, одежды и обуви, орг.техники, сотовых телефонов и акссесуаров и др.)', validators=[DataRequired()])
    noncx_store_needs = DecimalField('Магазин (минимаркет, строительных материалов, автозапчастей, одежды и обуви, орг.техники, сотовых телефонов и акссесуаров и др.)', validators=[DataRequired()])
    noncx_remont_bytovoi_tech = DecimalField('Мастерская, услуги по ремонту бытовой техники, орг.техники, инструментов, замена картриджей и т.д.', validators=[DataRequired()])
    noncx_remont_bytovoi_tech_needs = DecimalField('Мастерская, услуги по ремонту бытовой техники, орг.техники, инструментов, замена картриджей и т.д.', validators=[DataRequired()])
    noncx_metal = DecimalField('Металлопластиковые изделия', validators=[DataRequired()])
    noncx_metal_needs = DecimalField('Металлопластиковые изделия', validators=[DataRequired()])
    noncx_accounting = DecimalField('Оказание профессиональных услуг - бухгалтерские, юридические, налоговые, маркетинг, реклама и т.д', validators=[DataRequired()])
    noncx_accounting_needs = DecimalField('Оказание профессиональных услуг - бухгалтерские, юридические, налоговые, маркетинг, реклама и т.д', validators=[DataRequired()])
    noncx_photo = DecimalField('Полиграфические услуги, фотосалон, услуги фото-видео съемки', validators=[DataRequired()])
    noncx_photo_needs = DecimalField('Полиграфические услуги, фотосалон, услуги фото-видео съемки', validators=[DataRequired()])
    noncx_turism = DecimalField('Туризм (гостиницы, хостелы, кемпинги, турбазы)', validators=[DataRequired()])
    noncx_turism_needs = DecimalField('Туризм (гостиницы, хостелы, кемпинги, турбазы)', validators=[DataRequired()])
    noncx_rent = DecimalField('Услуги аренды (автотранспортных средств, оборудования, инструментов)', validators=[DataRequired()])
    noncx_rent_needs = DecimalField('Услуги аренды (автотранспортных средств, оборудования, инструментов)', validators=[DataRequired()])
    noncx_cargo = DecimalField('Услуги грузовых авто', validators=[DataRequired()])
    noncx_cargo_needs = DecimalField('Услуги грузовых авто', validators=[DataRequired()])
    noncx_massage = DecimalField('Услуги массажа, косметических, лечебных и оздоровительных процедур', validators=[DataRequired()])
    noncx_massage_needs = DecimalField('Услуги массажа, косметических, лечебных и оздоровительных процедур', validators=[DataRequired()])
    noncx_foodcourt = DecimalField('Услуги общепита (кафе, фаст-фуд, бистро, кофейни и т.д.)', validators=[DataRequired()])
    noncx_foodcourt_needs = DecimalField('Услуги общепита (кафе, фаст-фуд, бистро, кофейни и т.д.)', validators=[DataRequired()])
    noncx_cleaning = DecimalField('Услуги по уборке, озеленению, клининговые услуги и т.д.', validators=[DataRequired()])
    noncx_cleaning_needs = DecimalField('Услуги по уборке, озеленению, клининговые услуги и т.д.', validators=[DataRequired()])
    noncx_beuty = DecimalField('Услуги салонов красоты (парикмахерская, ногтевой сервис, маникюр, макияж)', validators=[DataRequired()])
    noncx_beuty_needs = DecimalField('Услуги салонов красоты (парикмахерская, ногтевой сервис, маникюр, макияж)', validators=[DataRequired()])
    noncx_carwash = DecimalField('Химчистка одежды, авто, мойка ковров и т.д.', validators=[DataRequired()])
    noncx_carwash_needs = DecimalField('Химчистка одежды, авто, мойка ковров и т.д.', validators=[DataRequired()])
    noncx_atelie = DecimalField('Швейный цех, ателье, вязальный цех, пошив и ремонт одежды, национальной одежды, головных уборов, кыз жасау, предметов быта', validators=[DataRequired()])
    noncx_atelie_needs = DecimalField('Швейный цех, ателье, вязальный цех, пошив и ремонт одежды, национальной одежды, головных уборов, кыз жасау, предметов быта', validators=[DataRequired()])
    noncx_others = DecimalField('Прочие виды услуг', validators=[DataRequired()])
    noncx_others_needs = DecimalField('Прочие виды услуг', validators=[DataRequired()])
    noncx_stroika = DecimalField('Строительные услуги', validators=[DataRequired()])
    noncx_stroika_needs = DecimalField('Строительные услуги', validators=[DataRequired()])
    noncx_mebel = DecimalField('Производство мебели', validators=[DataRequired()])
    noncx_mebel_needs = DecimalField('Производство мебели', validators=[DataRequired()])
    noncx_stroi_material = DecimalField('Производство строительных материалов', validators=[DataRequired()])
    noncx_stroi_material_needs = DecimalField('Производство строительных материалов', validators=[DataRequired()])
    noncx_svarka = DecimalField('Сварочный цех', validators=[DataRequired()])
    noncx_svarka_needs = DecimalField('Сварочный цех', validators=[DataRequired()])
    noncx_woodworking = DecimalField('Деревообработка', validators=[DataRequired()])
    noncx_woodworking_needs = DecimalField('Деревообработка', validators=[DataRequired()])
    noncx_others_uslugi = DecimalField('Прочие виды промышленности', validators=[DataRequired()])
    noncx_others_needs_uslugi = DecimalField('Прочие виды промышленности', validators=[DataRequired()])
    manufacture_milk = DecimalField('Переработка молока (предприятия)', validators=[DataRequired()])
    manufacture_milk_needs = DecimalField('Переработка молока (предприятия)', validators=[DataRequired()])
    manufacture_meat = DecimalField('Переработка мяса (предприятия)', validators=[DataRequired()])
    manufacture_meat_needs = DecimalField('Переработка мяса (предприятия)', validators=[DataRequired()])
    manufacture_vegetables = DecimalField('Переработка плодов, ягод, овощей, картофеля, дикорастущего сырья', validators=[DataRequired()])
    manufacture_vegetables_needs = DecimalField('Переработка плодов, ягод, овощей, картофеля, дикорастущего сырья', validators=[DataRequired()])
    manufacture_mayo = DecimalField('Производство майонеза, растительных масел', validators=[DataRequired()])
    manufacture_mayo_needs = DecimalField('Производство майонеза, растительных масел', validators=[DataRequired()])
    manufacture_fish = DecimalField('Переработка рыбы', validators=[DataRequired()])
    manufacture_fish_needs = DecimalField('Переработка рыбы', validators=[DataRequired()])
    manufacture_choco = DecimalField('Производство кондитерских изделий', validators=[DataRequired()])
    manufacture_choco_needs = DecimalField('Производство кондитерских изделий', validators=[DataRequired()])
    manufacture_beer = DecimalField('Производство пива и безалкогольных напитков', validators=[DataRequired()])
    manufacture_beer_needs = DecimalField('Производство пива и безалкогольных напитков', validators=[DataRequired()])
    manufacture_vodka = DecimalField('Производство ликеро-водочных изделий', validators=[DataRequired()])
    manufacture_vodka_needs = DecimalField('Производство ликеро-водочных изделий', validators=[DataRequired()])
    manufacture_honey = DecimalField('Продукция из меда', validators=[DataRequired()])
    manufacture_honey_needs = DecimalField('Продукция из меда', validators=[DataRequired()])
    manufacture_polufabricat = DecimalField('Производство полуфабрикатов (пельмени, манты, вареники, замороженные продукты и пр.)', validators=[DataRequired()])
    manufacture_polufabricat_needs = DecimalField('Производство полуфабрикатов (пельмени, манты, вареники, замороженные продукты и пр.)', validators=[DataRequired()])
    manufacture_bread = DecimalField('Производство хлебобулочных изделий', validators=[DataRequired()])
    manufacture_bread_needs = DecimalField('Производство хлебобулочных изделий', validators=[DataRequired()])
    manufacture_others = DecimalField('Прочее', validators=[DataRequired()])
    manufacture_others_needs = DecimalField('Прочее', validators=[DataRequired()])
    credit_amount = DecimalField('Количество заявок по направлениям кредита', validators=[DataRequired()])
    credit_total = DecimalField('Итого общая потребность в кредитах', validators=[DataRequired()])
    credit_average_total = DecimalField('Средний чек по кредиту', validators=[DataRequired()])
    credit_zalog = DecimalField('Количество обеспеченных залогом участников', validators=[DataRequired()]) # %

    submit = SubmitField('Отправить')
