from flask import session
from app import app, db, login_manager
from flask_login import UserMixin
from sqlalchemy.orm import relationship

@login_manager.user_loader
def load_user(user_id):
   return User.query.get(int(user_id))

class User(db.Model, UserMixin):
   id = db.Column(db.Integer, primary_key = True)
   kato_1 = db.Column(db.String(20), unique = True, nullable = False)
   kato_1_name = db.Column(db.String(20), unique = True, nullable = False)
   kato_2 = db.Column(db.String(20), unique = True, nullable = False)
   kato_2_name = db.Column(db.String(20), unique = True, nullable = False) 
   kato_3 = db.Column(db.String(20), unique = True, nullable = False)
   kato_3_name = db.Column(db.String(20), unique = True, nullable = False)
   username = db.Column(db.String(20), unique = True, nullable = False)
   first_name = db.Column(db.String(20), nullable = False)
   middle_name = db.Column(db.String(20), nullable = False)
   last_name = db.Column(db.String(20), nullable = False)
   district = db.Column(db.String(20), nullable = False)
   password = db.Column(db.String(250), nullable = False)
   def __repr__(self):
      return f"First_name('{self.first_name}'), Last_name('{self.last_name}'),  Username('{self.username}'), District('{self.district}')"

class Form(db.Model):
   id = db.Column(db.Integer, primary_key = True)
   user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
   user = relationship("User",backref="forms") 
   form_year = db.Column(db.String(10))
   labour_population = db.Column(db.Numeric(30, 10))
   labour_constant_population = db.Column(db.Numeric(30, 10))
   labour_labour = db.Column(db.Numeric(30, 10))
   labour_government_workers = db.Column(db.Numeric(30, 10))
   labour_private_labour = db.Column(db.Numeric(30, 10))
   labour_private_ogorod = db.Column(db.Numeric(30, 10))
   labour_total_econ_inactive_population = db.Column(db.Numeric(30, 10))
   labour_unemployed = db.Column(db.Numeric(30, 10))
   labour_household_size = db.Column(db.Numeric(30, 10))
   labour_average_income_family = db.Column(db.Numeric(30, 10))
   house_total_dvor = db.Column(db.Numeric(30, 10))
   house_zaselen_dvor = db.Column(db.Numeric(30, 10))
   dh_count = db.Column(db.Numeric(30, 10))
   dx_number_ogorodov = db.Column(db.Numeric(30, 10))
   dx_cx_land = db.Column(db.Numeric(30, 10))
   dx_pashnya = db.Column(db.Numeric(30, 10))
   dx_mnogoletnie = db.Column(db.Numeric(30, 10))
   dx_zelej = db.Column(db.Numeric(30, 10))
   dx_pastbishe = db.Column(db.Numeric(30, 10))
   dx_senokosy = db.Column(db.Numeric(30, 10))
   dx_ogorody = db.Column(db.Numeric(30, 10))
   dx_sad = db.Column(db.Numeric(30, 10))
   dx_urojai = db.Column(db.Numeric(30, 10))
   dx_cucumber = db.Column(db.Numeric(30, 10))
   dx_tomato = db.Column(db.Numeric(30, 10))
   dx_potato = db.Column(db.Numeric(30, 10))
   dx_kapusta = db.Column(db.Numeric(30, 10))
   dx_carrot = db.Column(db.Numeric(30, 10))
   dx_svekla = db.Column(db.Numeric(30, 10))
   dx_sweet_peper = db.Column(db.Numeric(30, 10))
   dx_baklajan = db.Column(db.Numeric(30, 10))
   dx_kabachek = db.Column(db.Numeric(30, 10))
   dx_onion = db.Column(db.Numeric(30, 10))
   dx_chesnok = db.Column(db.Numeric(30, 10))
   dx_redis = db.Column(db.Numeric(30, 10))
   dx_korm = db.Column(db.Numeric(30, 10))
   dx_fruits = db.Column(db.Numeric(30, 10))
   kx_amount = db.Column(db.Numeric(30, 10))
   kz_cx_land = db.Column(db.Numeric(30, 10))
   kx_pansya = db.Column(db.Numeric(30, 10))
   kx_mnogoletnie = db.Column(db.Numeric(30, 10))
   kx_zelej = db.Column(db.Numeric(30, 10))
   kx_pastbishe = db.Column(db.Numeric(30, 10))
   kx_senokosy = db.Column(db.Numeric(30, 10))
   kx_urojai = db.Column(db.Numeric(30, 10))
   kx_zerno = db.Column(db.Numeric(30, 10))
   kx_rice = db.Column(db.Numeric(30, 10))
   kx_maslichnye = db.Column(db.Numeric(30, 10))
   kx_korm = db.Column(db.Numeric(30, 10))
   kx_mnogoletnie_derevo = db.Column(db.Numeric(30, 10))
   kz_cx_land_reserve = db.Column(db.Numeric(30, 10))
   kx_pansya_reserve = db.Column(db.Numeric(30, 10))
   kx_mnogoletnie_reserve = db.Column(db.Numeric(30, 10))
   kx_zelej_reserve = db.Column(db.Numeric(30, 10))
   kx_pastbishe_reserve = db.Column(db.Numeric(30, 10))
   kx_senokosy_reserve = db.Column(db.Numeric(30, 10))
   infrastructure_polivochnaya_sistema_ = db.Column(db.Numeric(30, 10))
   infrastructure_polivochnaya_sistema_isused = db.Column(db.Numeric(30, 10))
   infrastructure_polivy = db.Column(db.Numeric(30, 10))
   infrastructure_mtm = db.Column(db.Numeric(30, 10))
   infrastructure_mtm_isused = db.Column(db.Numeric(30, 10))
   infrastructure_slad = db.Column(db.Numeric(30, 10))
   infrastructure_slad_isused = db.Column(db.Numeric(30, 10))
   infrastructure_garage = db.Column(db.Numeric(30, 10))
   infrastructure_garage_isused = db.Column(db.Numeric(30, 10))
   infrastructure_cycsterny = db.Column(db.Numeric(30, 10))
   infrastructure_cycsterny_isused = db.Column(db.Numeric(30, 10))
   infrastructure_transformator = db.Column(db.Numeric(30, 10))
   infrastructure_transformator_isused = db.Column(db.Numeric(30, 10))
   specialization_rastenivodstvo = db.Column(db.Numeric(30, 10))
   animal_dvor = db.Column(db.Numeric(30, 10))
   animal_skot_bird = db.Column(db.Numeric(30, 10))
   animal_cx_land = db.Column(db.Numeric(30, 10))
   animal_pashnya = db.Column(db.Numeric(30, 10))
   animal_mnogolet = db.Column(db.Numeric(30, 10))
   animal_zalej = db.Column(db.Numeric(30, 10))
   animal_pastbisha = db.Column(db.Numeric(30, 10))
   animal_senokos = db.Column(db.Numeric(30, 10))
   animal_ogorod = db.Column(db.Numeric(30, 10))
   animal_sad = db.Column(db.Numeric(30, 10))
   animal_krs_milk = db.Column(db.Numeric(30, 10))
   animal_krs_meat = db.Column(db.Numeric(30, 10))
   animal_sheep = db.Column(db.Numeric(30, 10))
   animal_kozel = db.Column(db.Numeric(30, 10))
   animal_horse = db.Column(db.Numeric(30, 10))
   animal_camel = db.Column(db.Numeric(30, 10))
   animal_pig = db.Column(db.Numeric(30, 10))
   animal_chicken = db.Column(db.Numeric(30, 10))
   animal_gusi = db.Column(db.Numeric(30, 10))
   animal_duck = db.Column(db.Numeric(30, 10))
   animal_induk = db.Column(db.Numeric(30, 10))
   animal_mik_total = db.Column(db.Numeric(30, 10))
   animal_milk_cow = db.Column(db.Numeric(30, 10))
   animal_milkrate_cow = db.Column(db.Numeric(30, 10))
   animal_mil_kozel = db.Column(db.Numeric(30, 10))
   animal_milrate_kozel = db.Column(db.Numeric(30, 10))
   animal_milk_horse = db.Column(db.Numeric(30, 10))
   animal_milkrate_horse = db.Column(db.Numeric(30, 10))
   animal_milk_camel = db.Column(db.Numeric(30, 10))
   animal_milkrate_camel = db.Column(db.Numeric(30, 10))
   animal_meat_total = db.Column(db.Numeric(30, 10))
   animal_meat_cow = db.Column(db.Numeric(30, 10))
   animal_meat_sheep = db.Column(db.Numeric(30, 10))
   animal_meat_horse = db.Column(db.Numeric(30, 10))
   animal_meat_pig = db.Column(db.Numeric(30, 10))
   animal_meat_camel = db.Column(db.Numeric(30, 10))
   animal_meat_chicken = db.Column(db.Numeric(30, 10))
   animal_meat_duck = db.Column(db.Numeric(30, 10))
   animal_meat_gusi = db.Column(db.Numeric(30, 10))
   animal_egg_total = db.Column(db.Numeric(30, 10))
   animal_egg_chicken = db.Column(db.Numeric(30, 10))
   animal_egg_gusi = db.Column(db.Numeric(30, 10))
   animal_egg_perepel = db.Column(db.Numeric(30, 10))
   animal_transformator = db.Column(db.Numeric(30, 10))
   animal_transformator_isused = db.Column(db.Numeric(30, 10))
   specialization_animal = db.Column(db.Numeric(30, 10))
   noncx_sto = db.Column(db.Numeric(30, 10))
   noncx_sto_needs = db.Column(db.Numeric(30, 10))
   noncx_kindergarden = db.Column(db.Numeric(30, 10))
   noncx_kindergarden_needs = db.Column(db.Numeric(30, 10))
   noncx_souvenier = db.Column(db.Numeric(30, 10))
   noncx_souvenier_needs = db.Column(db.Numeric(30, 10))
   noncx_pc_service = db.Column(db.Numeric(30, 10))
   noncx_pc_service_needs = db.Column(db.Numeric(30, 10))
   noncx_store = db.Column(db.Numeric(30, 10))
   noncx_store_needs = db.Column(db.Numeric(30, 10))
   noncx_remont_bytovoi_tech = db.Column(db.Numeric(30, 10))
   noncx_remont_bytovoi_tech_needs = db.Column(db.Numeric(30, 10))
   noncx_metal = db.Column(db.Numeric(30, 10))
   noncx_metal_needs = db.Column(db.Numeric(30, 10))
   noncx_accounting = db.Column(db.Numeric(30, 10))
   noncx_accounting_needs = db.Column(db.Numeric(30, 10))
   noncx_photo = db.Column(db.Numeric(30, 10))
   noncx_photo_needs = db.Column(db.Numeric(30, 10))
   noncx_turism = db.Column(db.Numeric(30, 10))
   noncx_turism_needs = db.Column(db.Numeric(30, 10))
   noncx_rent = db.Column(db.Numeric(30, 10))
   noncx_rent_needs = db.Column(db.Numeric(30, 10))
   noncx_cargo = db.Column(db.Numeric(30, 10))
   noncx_cargo_needs = db.Column(db.Numeric(30, 10))
   noncx_massage = db.Column(db.Numeric(30, 10))
   noncx_massage_needs = db.Column(db.Numeric(30, 10))
   noncx_foodcourt = db.Column(db.Numeric(30, 10))
   noncx_foodcourt_needs = db.Column(db.Numeric(30, 10))
   noncx_cleaning = db.Column(db.Numeric(30, 10))
   noncx_cleaning_needs = db.Column(db.Numeric(30, 10))
   noncx_beuty = db.Column(db.Numeric(30, 10))
   noncx_beuty_needs = db.Column(db.Numeric(30, 10))
   noncx_carwash = db.Column(db.Numeric(30, 10))
   noncx_carwash_needs = db.Column(db.Numeric(30, 10))
   noncx_atelie = db.Column(db.Numeric(30, 10))
   noncx_atelie_needs = db.Column(db.Numeric(30, 10))
   noncx_others = db.Column(db.Numeric(30, 10))
   noncx_others_needs = db.Column(db.Numeric(30, 10))
   noncx_stroika = db.Column(db.Numeric(30, 10))
   noncx_stroika_needs = db.Column(db.Numeric(30, 10))
   noncx_mebel = db.Column(db.Numeric(30, 10))
   noncx_mebel_needs = db.Column(db.Numeric(30, 10))
   noncx_stroi_material = db.Column(db.Numeric(30, 10))
   noncx_stroi_material_needs = db.Column(db.Numeric(30, 10))
   noncx_svarka = db.Column(db.Numeric(30, 10))
   noncx_svarka_needs = db.Column(db.Numeric(30, 10))
   noncx_woodworking = db.Column(db.Numeric(30, 10))
   noncx_woodworking_needs = db.Column(db.Numeric(30, 10))
   noncx_others_uslugi = db.Column(db.Numeric(30, 10))
   noncx_others_needs_uslugi = db.Column(db.Numeric(30, 10))
   manufacture_milk = db.Column(db.Numeric(30, 10))
   manufacture_milk_needs = db.Column(db.Numeric(30, 10))
   manufacture_meat = db.Column(db.Numeric(30, 10))
   manufacture_meat_needs = db.Column(db.Numeric(30, 10))
   manufacture_vegetables = db.Column(db.Numeric(30, 10))  # Corrected typo
   manufacture_vegetables_needs = db.Column(db.Numeric(30, 10))  # Corrected typo
   manufacture_mayo = db.Column(db.Numeric(30, 10))
   manufacture_mayo_needs = db.Column(db.Numeric(30, 10))
   manufacture_fish = db.Column(db.Numeric(30, 10))
   manufacture_fish_needs = db.Column(db.Numeric(30, 10))
   manufacture_choco = db.Column(db.Numeric(30, 10))
   manufacture_choco_needs = db.Column(db.Numeric(30, 10))
   manufacture_beer = db.Column(db.Numeric(30, 10))
   manufacture_beer_needs = db.Column(db.Numeric(30, 10))
   manufacture_vodka = db.Column(db.Numeric(30, 10))
   manufacture_vodka_needs = db.Column(db.Numeric(30, 10))
   manufacture_honey = db.Column(db.Numeric(30, 10))
   manufacture_honey_needs = db.Column(db.Numeric(30, 10))
   manufacture_polufabricat = db.Column(db.Numeric(30, 10))
   manufacture_polufabricat_needs = db.Column(db.Numeric(30, 10))
   manufacture_bread = db.Column(db.Numeric(30, 10))
   manufacture_bread_needs = db.Column(db.Numeric(30, 10))
   manufacture_others = db.Column(db.Numeric(30, 10))
   manufacture_others_needs = db.Column(db.Numeric(30, 10))
   credit_amount = db.Column(db.Numeric(30, 10))
   credit_total = db.Column(db.Numeric(30, 10))
   credit_average_total = db.Column(db.Numeric(30, 10))
   credit_zalog = db.Column(db.Numeric(30, 10))
   modified_date = db.Column(db.TIMESTAMP(timezone=True), default=db.func.now(), onupdate=db.func.now())

with app.app_context():
    db.create_all()
