from flask import flash, redirect, render_template, url_for, request
from app.forms import *
from app.models import *
from app import app, db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime



@app.route('/')
def home():
    return render_template('base.html', user=current_user)

@app.route('/login',  methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('home'))
        else:
            flash('Неверный логин или пароль! Попробуйте еще раз', 'danger')
    return render_template('login.html', title='Login', form=form, user=current_user)

@app.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('home'))

@app.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    formdata = Form.query.filter_by(user_id=current_user.id).all()
    return render_template('account.html', title = 'Личный кабинет', user=current_user, formdata=formdata)

@app.route('/account/<id>/edit', methods=['POST', 'GET'])
def edit_form(id):
    form = FormDataForm()
    formdata = Form.query.filter_by(id=id).first()
    if request.method == 'GET':
        return render_template('edit_form.html', form=form, user=current_user)
    else:
        if form.validate_on_submit():
            formdata.labour_population=form.labour_population.data,
            formdata.labour_constant_population=form.labour_constant_population.data,
            formdata.labour_labour=form.labour_labour.data,
            formdata.labour_goverment_workers=form.labour_goverment_workers.data,
            formdata.labour_private_labour=form.labour_private_labour.data,
            formdata.labour_private_ogorod=form.labour_private_ogorod.data,
            formdata.labour_total_econ_inactive_population=form.labour_total_econ_inactive_population.data,
            formdata.labour_unemployed=form.labour_unemployed.data,
            formdata.labour_household_size=form.labour_household_size.data,
            formdata.labour_average_income_family=form.labour_average_income_family.data,
            formdata.house_total_dvor=form.house_total_dvor.data,
            formdata.house_zaselen_dvor=form.house_zaselen_dvor.data,
            formdata.dh_count=form.dh_count.data,
            formdata.dx_number_ogorodov=form.dx_number_ogorodov.data,
            formdata.dx_cx_land=form.dx_cx_land.data,
            formdata.dx_pashnya=form.dx_pashnya.data,
            formdata.dx_mnogoletnie=form.dx_mnogoletnie.data,
            formdata.dx_zelej=form.dx_zelej.data,
            formdata.dx_pastbishe=form.dx_pastbishe.data,
            formdata.dx_senokosy=form.dx_senokosy.data,
            formdata.dx_ogorody=form.dx_ogorody.data,
            formdata.dx_sad=form.dx_sad.data,
            formdata.dx_urojai=form.dx_urojai.data,
            formdata.dx_cucumber=form.dx_cucumber.data,
            formdata.dx_tomato=form.dx_tomato.data,
            formdata.dx_potato=form.dx_potato.data,
            formdata.dx_kapusta=form.dx_kapusta.data,
            formdata.dx_carrot=form.dx_carrot.data,
            formdata.dx_svekla=form.dx_svekla.data,
            formdata.dx_sweet_peper=form.dx_sweet_peper.data,
            formdata.dx_baklajan=form.dx_baklajan.data,
            formdata.dx_kabachek=form.dx_kabachek.data,
            formdata.dx_onion=form.dx_onion.data,
            formdata.dx_chesnok=form.dx_chesnok.data,
            formdata.dx_redis=form.dx_redis.data,
            formdata.dx_korm=form.dx_korm.data,
            formdata.dx_fruits=form.dx_fruits.data,
            formdata.kx_amount=form.kx_amount.data,
            formdata.kz_cx_land=form.kz_cx_land.data,
            formdata.kx_pansya=form.kx_pansya.data,
            formdata.kx_mnogoletnie=form.kx_mnogoletnie.data,
            formdata.kx_zelej=form.kx_zelej.data,
            formdata.kx_pastbishe=form.kx_pastbishe.data,
            formdata.kx_senokosy=form.kx_senokosy.data,
            formdata.kx_urojai=form.kx_urojai.data,
            formdata.kx_zerno=form.kx_zerno.data,
            formdata.kx_rice=form.kx_rice.data,
            formdata.kx_maslichnye=form.kx_maslichnye.data,
            formdata.kx_korm=form.kx_korm.data,
            formdata.kx_mnogoletnie_derevo=form.kx_mnogoletnie_derevo.data,
            formdata.kz_cx_land_reserve=form.kz_cx_land_reserve.data,
            formdata.kx_pansya_reserve=form.kx_pansya_reserve.data,
            formdata.kx_mnogoletnie_reserve=form.kx_mnogoletnie_reserve.data,
            formdata.kx_zelej_reserve=form.kx_zelej_reserve.data,
            formdata.kx_pastbishe_reserve=form.kx_pastbishe_reserve.data,
            formdata.kx_senokosy_reserve=form.kx_senokosy_reserve.data,
            formdata.infrastructure_polivochnaya_sistema_=form.infrastructure_polivochnaya_sistema_.data,
            formdata.infrastructure_polivochnaya_sistema_isused=form.infrastructure_polivochnaya_sistema_isused.data,
            formdata.infrastructure_polivy=form.infrastructure_polivy.data,
            formdata.infrastructure_mtm=form.infrastructure_mtm.data,
            formdata.infrastructure_mtm_isused=form.infrastructure_mtm_isused.data,
            formdata.infrastructure_slad=form.infrastructure_slad.data,
            formdata.infrastructure_slad_isused=form.infrastructure_slad_isused.data,
            formdata.infrastructure_garage=form.infrastructure_garage.data,
            formdata.infrastructure_garage_isused=form.infrastructure_garage_isused.data,
            formdata.infrastructure_cycsterny=form.infrastructure_cycsterny.data,
            formdata.infrastructure_cycsterny_isused=form.infrastructure_cycsterny_isused.data,
            formdata.infrastructure_transformator=form.infrastructure_transformator.data,
            formdata.infrastructure_transformator_isused=form.infrastructure_transformator_isused.data,
            formdata.specialization_rastenivodstvo=form.specialization_rastenivodstvo.data,
            formdata.animal_dvor=form.animal_dvor.data,
            formdata.animal_skot_bird=form.animal_skot_bird.data,
            formdata.animal_cx_land=form.animal_cx_land.data,
            formdata.animal_pashnya=form.animal_pashnya.data,
            formdata.animal_mnogolet=form.animal_mnogolet.data,
            formdata.animal_zalej=form.animal_zalej.data,
            formdata.animal_pastbisha=form.animal_pastbisha.data,
            formdata.animal_senokos=form.animal_senokos.data,
            formdata.animal_ogorod=form.animal_ogorod.data,
            formdata.animal_sad=form.animal_sad.data,
            formdata.animal_krs_milk=form.animal_krs_milk.data,
            formdata.animal_krs_meat=form.animal_krs_meat.data,
            formdata.animal_sheep=form.animal_sheep.data,
            formdata.animal_kozel=form.animal_kozel.data,
            formdata.animal_horse=form.animal_horse.data,
            formdata.animal_camel=form.animal_camel.data,
            formdata.animal_pig=form.animal_pig.data,
            formdata.animal_chicken=form.animal_chicken.data,
            formdata.animal_gusi=form.animal_gusi.data,
            formdata.animal_duck=form.animal_duck.data,
            formdata.animal_induk=form.animal_induk.data,
            formdata.animal_mik_total=form.animal_mik_total.data,
            formdata.animal_milk_cow=form.animal_milk_cow.data,
            formdata.animal_milkrate_cow=form.animal_milkrate_cow.data,
            formdata.animal_mil_kozel=form.animal_mil_kozel.data,
            formdata.animal_milrate_kozel=form.animal_milrate_kozel.data,
            formdata.animal_milk_horse=form.animal_milk_horse.data,
            formdata.animal_milkrate_horse=form.animal_milkrate_horse.data,
            formdata.animal_milk_camel=form.animal_milk_camel.data,
            formdata.animal_milkrate_camel=form.animal_milkrate_camel.data,
            formdata.animal_meat_total=form.animal_meat_total.data,
            formdata.animal_meat_cow=form.animal_meat_cow.data,
            formdata.animal_meat_sheep=form.animal_meat_sheep.data,
            formdata.animal_meat_horse=form.animal_meat_horse.data,
            formdata.animal_meat_pig=form.animal_meat_pig.data,
            formdata.animal_meat_camel=form.animal_meat_camel.data,
            formdata.animal_meat_chicken=form.animal_meat_chicken.data,
            formdata.animal_meat_duck=form.animal_meat_duck.data,
            formdata.animal_meat_gusi=form.animal_meat_gusi.data,
            formdata.animal_egg_total=form.animal_egg_total.data,
            formdata.animal_egg_chicken=form.animal_egg_chicken.data,
            formdata.animal_egg_gusi=form.animal_egg_gusi.data,
            formdata.animal_egg_perepel=form.animal_egg_perepel.data,
            formdata.animal_transformator=form.animal_transformator.data,
            formdata.animal_transformator_isused=form.animal_transformator_isused.data,
            formdata.specialization_animal=form.specialization_animal.data,
            formdata.noncx_sto=form.noncx_sto.data,
            formdata.noncx_sto_needs=form.noncx_sto_needs.data,
            formdata.noncx_kindergarden=form.noncx_kindergarden.data,
            formdata.noncx_kindergarden_needs=form.noncx_kindergarden_needs.data,
            formdata.noncx_souvenier=form.noncx_souvenier.data,
            formdata.noncx_souvenier_needs=form.noncx_souvenier_needs.data,
            formdata.noncx_pc_service=form.noncx_pc_service.data,
            formdata.noncx_pc_service_needs=form.noncx_pc_service_needs.data,
            formdata.noncx_store=form.noncx_store.data,
            formdata.noncx_store_needs=form.noncx_store_needs.data,
            formdata.noncx_remont_bytovoi_tech=form.noncx_remont_bytovoi_tech.data,
            formdata.noncx_remont_bytovoi_tech_needs=form.noncx_remont_bytovoi_tech_needs.data,
            formdata.noncx_metal=form.noncx_metal.data,
            formdata.noncx_metal_needs=form.noncx_metal_needs.data,
            formdata.noncx_accounting=form.noncx_accounting.data,
            formdata.noncx_accounting_needs=form.noncx_accounting_needs.data,
            formdata.noncx_photo=form.noncx_photo.data,
            formdata.noncx_photo_needs=form.noncx_photo_needs.data,
            formdata.noncx_turism=form.noncx_turism.data,
            formdata.noncx_turism_needs=form.noncx_turism_needs.data,
            formdata.noncx_rent=form.noncx_rent.data,
            formdata.noncx_rent_needs=form.noncx_rent_needs.data,
            formdata.noncx_cargo=form.noncx_cargo.data,
            formdata.noncx_cargo_needs=form.noncx_cargo_needs.data,
            formdata.noncx_massage=form.noncx_massage.data,
            formdata.noncx_massage_needs=form.noncx_massage_needs.data,
            formdata.noncx_foodcourt=form.noncx_foodcourt.data,
            formdata.noncx_foodcourt_needs=form.noncx_foodcourt_needs.data,
            formdata.noncx_cleaning=form.noncx_cleaning.data,
            formdata.noncx_cleaning_needs=form.noncx_cleaning_needs.data,
            formdata.noncx_beuty=form.noncx_beuty.data,
            formdata.noncx_beuty_needs=form.noncx_beuty_needs.data,
            formdata.noncx_carwash=form.noncx_carwash.data,
            formdata.noncx_carwash_needs=form.noncx_carwash_needs.data,
            formdata.noncx_atelie=form.noncx_atelie.data,
            formdata.noncx_atelie_needs=form.noncx_atelie_needs.data,
            formdata.noncx_others=form.noncx_others.data,
            formdata.noncx_others_needs=form.noncx_others_needs.data,
            formdata.noncx_stroika=form.noncx_stroika.data,
            formdata.noncx_stroika_needs=form.noncx_stroika_needs.data,
            formdata.noncx_mebel=form.noncx_mebel.data,
            formdata.noncx_mebel_needs=form.noncx_mebel_needs.data,
            formdata.noncx_stroi_material=form.noncx_stroi_material.data,
            formdata.noncx_stroi_material_needs=form.noncx_stroi_material_needs.data,
            formdata.noncx_svarka=form.noncx_svarka.data,
            formdata.noncx_svarka_needs=form.noncx_svarka_needs.data,
            formdata.noncx_woodworking=form.noncx_woodworking.data,
            formdata.noncx_woodworking_needs=form.noncx_woodworking_needs.data,
            formdata.noncx_others_uslugi=form.noncx_others_uslugi.data,
            formdata.noncx_others_needs_uslugi=form.noncx_others_needs_uslugi.data,
            formdata.manufacture_milk=form.manufacture_milk.data,
            formdata.manufacture_milk_needs=form.manufacture_milk_needs.data,
            formdata.manufacture_meat=form.manufacture_meat.data,
            formdata.manufacture_meat_needs=form.manufacture_meat_needs.data,
            formdata.manufacture_vegetables=form.manufacture_vegetables.data,
            formdata.manufacture_vegetables_needs=form.manufacture_vegetables_needs.data,
            formdata.manufacture_mayo=form.manufacture_mayo.data,
            formdata.manufacture_mayo_needs=form.manufacture_mayo_needs.data,
            formdata.manufacture_fish=form.manufacture_fish.data,
            formdata.manufacture_fish_needs=form.manufacture_fish_needs.data,
            formdata.manufacture_choco=form.manufacture_choco.data,
            formdata.manufacture_choco_needs=form.manufacture_choco_needs.data,
            formdata.manufacture_beer=form.manufacture_beer.data,
            formdata.manufacture_beer_needs=form.manufacture_beer_needs.data,
            formdata.manufacture_vodka=form.manufacture_vodka.data,
            formdata.manufacture_vodka_needs=form.manufacture_vodka_needs.data,
            formdata.manufacture_honey=form.manufacture_honey.data,
            formdata.manufacture_honey_needs=form.manufacture_honey_needs.data,
            formdata.manufacture_polufabricat=form.manufacture_polufabricat.data,
            formdata.manufacture_polufabricat_needs=form.manufacture_polufabricat_needs.data,
            formdata.manufacture_bread=form.manufacture_bread.data,
            formdata.manufacture_bread_needs=form.manufacture_bread_needs.data,
            formdata.manufacture_others=form.manufacture_others.data,
            formdata.manufacture_others_needs=form.manufacture_others_needs.data,
            formdata.credit_amount=form.credit_amount.data,
            formdata.credit_total=form.credit_total.data,
            formdata.credit_average_total=form.credit_average_total.data,
            formdata.credit_zalog=form.credit_zalog.data
            db.session.commit()
            flash("Данные успешно изменены!", 'success')
            return redirect(url_for('account'))
        else:
            flash("Данные не изменены! Некорректный формат.", 'danger')
            return render_template('edit_form.html', form=form, user=current_user)


@app.route('/form', methods=['POST', 'GET'])
@login_required
def form():
    user = current_user
    form = FormDataForm()
    if request.method == "GET":
        return render_template('ms_form.html', form=form, user=user)
    else:
        if form.validate_on_submit():
            formdata = Form(
                user_id = user.id,
                form_year = datetime.now().year,
                labour_population=form.labour_population.data,
                labour_constant_population=form.labour_constant_population.data,
                labour_labour=form.labour_labour.data,
                labour_goverment_workers=form.labour_goverment_workers.data,
                labour_private_labour=form.labour_private_labour.data,
                labour_private_ogorod=form.labour_private_ogorod.data,
                labour_total_econ_inactive_population=form.labour_total_econ_inactive_population.data,
                labour_unemployed=form.labour_unemployed.data,
                labour_household_size=form.labour_household_size.data,
                labour_average_income_family=form.labour_average_income_family.data,
                house_total_dvor=form.house_total_dvor.data,
                house_zaselen_dvor=form.house_zaselen_dvor.data,
                dh_count=form.dh_count.data,
                dx_number_ogorodov=form.dx_number_ogorodov.data,
                dx_cx_land=form.dx_cx_land.data,
                dx_pashnya=form.dx_pashnya.data,
                dx_mnogoletnie=form.dx_mnogoletnie.data,
                dx_zelej=form.dx_zelej.data,
                dx_pastbishe=form.dx_pastbishe.data,
                dx_senokosy=form.dx_senokosy.data,
                dx_ogorody=form.dx_ogorody.data,
                dx_sad=form.dx_sad.data,
                dx_urojai=form.dx_urojai.data,
                dx_cucumber=form.dx_cucumber.data,
                dx_tomato=form.dx_tomato.data,
                dx_potato=form.dx_potato.data,
                dx_kapusta=form.dx_kapusta.data,
                dx_carrot=form.dx_carrot.data,
                dx_svekla=form.dx_svekla.data,
                dx_sweet_peper=form.dx_sweet_peper.data,
                dx_baklajan=form.dx_baklajan.data,
                dx_kabachek=form.dx_kabachek.data,
                dx_onion=form.dx_onion.data,
                dx_chesnok=form.dx_chesnok.data,
                dx_redis=form.dx_redis.data,
                dx_korm=form.dx_korm.data,
                dx_fruits=form.dx_fruits.data,
                kx_amount=form.kx_amount.data,
                kz_cx_land=form.kz_cx_land.data,
                kx_pansya=form.kx_pansya.data,
                kx_mnogoletnie=form.kx_mnogoletnie.data,
                kx_zelej=form.kx_zelej.data,
                kx_pastbishe=form.kx_pastbishe.data,
                kx_senokosy=form.kx_senokosy.data,
                kx_urojai=form.kx_urojai.data,
                kx_zerno=form.kx_zerno.data,
                kx_rice=form.kx_rice.data,
                kx_maslichnye=form.kx_maslichnye.data,
                kx_korm=form.kx_korm.data,
                kx_mnogoletnie_derevo=form.kx_mnogoletnie_derevo.data,
                kz_cx_land_reserve=form.kz_cx_land_reserve.data,
                kx_pansya_reserve=form.kx_pansya_reserve.data,
                kx_mnogoletnie_reserve=form.kx_mnogoletnie_reserve.data,
                kx_zelej_reserve=form.kx_zelej_reserve.data,
                kx_pastbishe_reserve=form.kx_pastbishe_reserve.data,
                kx_senokosy_reserve=form.kx_senokosy_reserve.data,
                infrastructure_polivochnaya_sistema_=form.infrastructure_polivochnaya_sistema_.data,
                infrastructure_polivochnaya_sistema_isused=form.infrastructure_polivochnaya_sistema_isused.data,
                infrastructure_polivy=form.infrastructure_polivy.data,
                infrastructure_mtm=form.infrastructure_mtm.data,
                infrastructure_mtm_isused=form.infrastructure_mtm_isused.data,
                infrastructure_slad=form.infrastructure_slad.data,
                infrastructure_slad_isused=form.infrastructure_slad_isused.data,
                infrastructure_garage=form.infrastructure_garage.data,
                infrastructure_garage_isused=form.infrastructure_garage_isused.data,
                infrastructure_cycsterny=form.infrastructure_cycsterny.data,
                infrastructure_cycsterny_isused=form.infrastructure_cycsterny_isused.data,
                infrastructure_transformator=form.infrastructure_transformator.data,
                infrastructure_transformator_isused=form.infrastructure_transformator_isused.data,
                specialization_rastenivodstvo=form.specialization_rastenivodstvo.data,
                animal_dvor=form.animal_dvor.data,
                animal_skot_bird=form.animal_skot_bird.data,
                animal_cx_land=form.animal_cx_land.data,
                animal_pashnya=form.animal_pashnya.data,
                animal_mnogolet=form.animal_mnogolet.data,
                animal_zalej=form.animal_zalej.data,
                animal_pastbisha=form.animal_pastbisha.data,
                animal_senokos=form.animal_senokos.data,
                animal_ogorod=form.animal_ogorod.data,
                animal_sad=form.animal_sad.data,
                animal_krs_milk=form.animal_krs_milk.data,
                animal_krs_meat=form.animal_krs_meat.data,
                animal_sheep=form.animal_sheep.data,
                animal_kozel=form.animal_kozel.data,
                animal_horse=form.animal_horse.data,
                animal_camel=form.animal_camel.data,
                animal_pig=form.animal_pig.data,
                animal_chicken=form.animal_chicken.data,
                animal_gusi=form.animal_gusi.data,
                animal_duck=form.animal_duck.data,
                animal_induk=form.animal_induk.data,
                animal_mik_total=form.animal_mik_total.data,
                animal_milk_cow=form.animal_milk_cow.data,
                animal_milkrate_cow=form.animal_milkrate_cow.data,
                animal_mil_kozel=form.animal_mil_kozel.data,
                animal_milrate_kozel=form.animal_milrate_kozel.data,
                animal_milk_horse=form.animal_milk_horse.data,
                animal_milkrate_horse=form.animal_milkrate_horse.data,
                animal_milk_camel=form.animal_milk_camel.data,
                animal_milkrate_camel=form.animal_milkrate_camel.data,
                animal_meat_total=form.animal_meat_total.data,
                animal_meat_cow=form.animal_meat_cow.data,
                animal_meat_sheep=form.animal_meat_sheep.data,
                animal_meat_horse=form.animal_meat_horse.data,
                animal_meat_pig=form.animal_meat_pig.data,
                animal_meat_camel=form.animal_meat_camel.data,
                animal_meat_chicken=form.animal_meat_chicken.data,
                animal_meat_duck=form.animal_meat_duck.data,
                animal_meat_gusi=form.animal_meat_gusi.data,
                animal_egg_total=form.animal_egg_total.data,
                animal_egg_chicken=form.animal_egg_chicken.data,
                animal_egg_gusi=form.animal_egg_gusi.data,
                animal_egg_perepel=form.animal_egg_perepel.data,
                animal_transformator=form.animal_transformator.data,
                animal_transformator_isused=form.animal_transformator_isused.data,
                specialization_animal=form.specialization_animal.data,
                noncx_sto=form.noncx_sto.data,
                noncx_sto_needs=form.noncx_sto_needs.data,
                noncx_kindergarden=form.noncx_kindergarden.data,
                noncx_kindergarden_needs=form.noncx_kindergarden_needs.data,
                noncx_souvenier=form.noncx_souvenier.data,
                noncx_souvenier_needs=form.noncx_souvenier_needs.data,
                noncx_pc_service=form.noncx_pc_service.data,
                noncx_pc_service_needs=form.noncx_pc_service_needs.data,
                noncx_store=form.noncx_store.data,
                noncx_store_needs=form.noncx_store_needs.data,
                noncx_remont_bytovoi_tech=form.noncx_remont_bytovoi_tech.data,
                noncx_remont_bytovoi_tech_needs=form.noncx_remont_bytovoi_tech_needs.data,
                noncx_metal=form.noncx_metal.data,
                noncx_metal_needs=form.noncx_metal_needs.data,
                noncx_accounting=form.noncx_accounting.data,
                noncx_accounting_needs=form.noncx_accounting_needs.data,
                noncx_photo=form.noncx_photo.data,
                noncx_photo_needs=form.noncx_photo_needs.data,
                noncx_turism=form.noncx_turism.data,
                noncx_turism_needs=form.noncx_turism_needs.data,
                noncx_rent=form.noncx_rent.data,
                noncx_rent_needs=form.noncx_rent_needs.data,
                noncx_cargo=form.noncx_cargo.data,
                noncx_cargo_needs=form.noncx_cargo_needs.data,
                noncx_massage=form.noncx_massage.data,
                noncx_massage_needs=form.noncx_massage_needs.data,
                noncx_foodcourt=form.noncx_foodcourt.data,
                noncx_foodcourt_needs=form.noncx_foodcourt_needs.data,
                noncx_cleaning=form.noncx_cleaning.data,
                noncx_cleaning_needs=form.noncx_cleaning_needs.data,
                noncx_beuty=form.noncx_beuty.data,
                noncx_beuty_needs=form.noncx_beuty_needs.data,
                noncx_carwash=form.noncx_carwash.data,
                noncx_carwash_needs=form.noncx_carwash_needs.data,
                noncx_atelie=form.noncx_atelie.data,
                noncx_atelie_needs=form.noncx_atelie_needs.data,
                noncx_others=form.noncx_others.data,
                noncx_others_needs=form.noncx_others_needs.data,
                noncx_stroika=form.noncx_stroika.data,
                noncx_stroika_needs=form.noncx_stroika_needs.data,
                noncx_mebel=form.noncx_mebel.data,
                noncx_mebel_needs=form.noncx_mebel_needs.data,
                noncx_stroi_material=form.noncx_stroi_material.data,
                noncx_stroi_material_needs=form.noncx_stroi_material_needs.data,
                noncx_svarka=form.noncx_svarka.data,
                noncx_svarka_needs=form.noncx_svarka_needs.data,
                noncx_woodworking=form.noncx_woodworking.data,
                noncx_woodworking_needs=form.noncx_woodworking_needs.data,
                noncx_others_uslugi=form.noncx_others_uslugi.data,
                noncx_others_needs_uslugi=form.noncx_others_needs_uslugi.data,
                manufacture_milk=form.manufacture_milk.data,
                manufacture_milk_needs=form.manufacture_milk_needs.data,
                manufacture_meat=form.manufacture_meat.data,
                manufacture_meat_needs=form.manufacture_meat_needs.data,
                manufacture_vegetables=form.manufacture_vegetables.data,
                manufacture_vegetables_needs=form.manufacture_vegetables_needs.data,
                manufacture_mayo=form.manufacture_mayo.data,
                manufacture_mayo_needs=form.manufacture_mayo_needs.data,
                manufacture_fish=form.manufacture_fish.data,
                manufacture_fish_needs=form.manufacture_fish_needs.data,
                manufacture_choco=form.manufacture_choco.data,
                manufacture_choco_needs=form.manufacture_choco_needs.data,
                manufacture_beer=form.manufacture_beer.data,
                manufacture_beer_needs=form.manufacture_beer_needs.data,
                manufacture_vodka=form.manufacture_vodka.data,
                manufacture_vodka_needs=form.manufacture_vodka_needs.data,
                manufacture_honey=form.manufacture_honey.data,
                manufacture_honey_needs=form.manufacture_honey_needs.data,
                manufacture_polufabricat=form.manufacture_polufabricat.data,
                manufacture_polufabricat_needs=form.manufacture_polufabricat_needs.data,
                manufacture_bread=form.manufacture_bread.data,
                manufacture_bread_needs=form.manufacture_bread_needs.data,
                manufacture_others=form.manufacture_others.data,
                manufacture_others_needs=form.manufacture_others_needs.data,
                credit_amount=form.credit_amount.data,
                credit_total=form.credit_total.data,
                credit_average_total=form.credit_average_total.data,
                credit_zalog=form.credit_zalog.data
            )
            db.session.add(formdata)
            db.session.commit()
            flash("Форма успешено добавлена!", 'success')
            return redirect(url_for('home'))
    return render_template('ms_form.html', title='Форма отчетности МСХ', user=current_user)
